name: Claude AI Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned]
  pull_request_review:
    types: [submitted]

jobs:
  claude-assistant:
    name: Claude Assistant
    if: github.event_name != 'pull_request' || github.event.action != 'synchronize'
    runs-on: ubuntu-latest
    steps:
      - name: Run Claude Assistant with /claude trigger
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          trigger_phrase: "@claude"
