name: Auto Documentation Update

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  push:
    branches: ["main"]
    paths:
      - "smartspace/blocks/**"
      - "docs/utils/block_doc_generator.py"
      - "docs/utils/sync_and_generate_docs.py"
  workflow_dispatch:
    inputs:
      skip_sync:
        description: 'Skip repository sync'
        required: false
        type: boolean
        default: false

jobs:
  update-docs:
    name: Update Block Documentation
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.generate_docs.outputs.changes }}
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          pip install pyyaml
      
      - name: Run sync and documentation generation
        id: generate_docs
        run: |
          if [[ "${{ github.event.inputs.skip_sync }}" == "true" ]]; then
            python docs/utils/sync_and_generate_docs.py --skip-sync
          else
            python docs/utils/sync_and_generate_docs.py
          fi
          
          # Check if there are any changes
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Create Pull Request
        if: steps.generate_docs.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update block documentation"
          title: "Update Block Documentation"
          body: |
            This PR updates the block documentation based on the latest changes in the external repository.
            
            ## Changes
            - Synced blocks from [Smartspace-ai-api](https://github.com/Smartspace-ai/Smartspace-ai-api)
            - Generated/updated documentation for new or modified blocks
            - Updated mkdocs.yml navigation if new blocks were added
            
            Please review the changes and merge if everything looks correct.
          branch: update-block-docs
          delete-branch: true
          labels: |
            documentation
            automated

      - name: Upload temporary block sources as artifact
        uses: actions/upload-artifact@v4
        with:
          name: temp-block-sources
          path: docs/utils/smartspace_blocks/
          if-no-files-found: error

  enhance-docs-with-claude:
    name: Enhance Documentation with Claude
    needs: update-docs
    if: needs.update-docs.outputs.changes == 'true'
    runs-on: ubuntu-latest
    
    steps:
      - name: Download temporary block sources artifact
        uses: actions/download-artifact@v4
        with:
          name: temp-block-sources
          path: docs/utils/smartspace_blocks/

      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: update-block-docs
          fetch-depth: 0
      
      - name: Get changed documentation files
        id: changed_files
        run: |
          # Get list of changed .md files in block-reference directory
          CHANGED_DOCS=$(git diff --name-only origin/main...HEAD | grep '^docs/block-reference/.*\.md$' | grep -v 'BLOCK-TEMPLATE' | tr '\n' ' ' | sed 's/ $//')
          
          if [[ -z "$CHANGED_DOCS" ]]; then
            echo "No documentation files changed"
            echo "files=''" >> $GITHUB_OUTPUT
          else
            echo "Found changed documentation files: $CHANGED_DOCS"
            echo "files=$CHANGED_DOCS" >> $GITHUB_OUTPUT
          fi
      
      - name: Create dynamic prompt for Claude
        if: steps.changed_files.outputs.files != ''
        id: dynamic_prompt
        run: |
          PROMPT_HEADER="You are a meticulous technical writer responsible for ensuring all block documentation in our system is up to standard.
          To create high-quality examples and accurate documentation, you MUST read and analyze the content of the corresponding block's source code.
          The source code for new/updated blocks can be found in 'docs/utils/smartspace_blocks/', and for existing blocks in 'smartspace/blocks/'.
          Use this source code as the ground truth to understand parameters, logic, return values, and potential exceptions before you begin writing.

          Your task is to review and enhance ONLY the following documentation files: ${{ steps.changed_files.outputs.files }}
          
          For each file:
          1. Add meaningful examples in the Example(s) section that demonstrate real-world usage
          2. Add comprehensive error handling information
          3. Add relevant FAQ entries that users might have
          4. Ensure the documentation is clear, complete, and helpful
          5. Preserve the existing structure and any auto-generated content
          
          Focus on making the documentation practical and user-friendly.
          The files to enhance are: ${{ steps.changed_files.outputs.files }}
          ---
          Here are the guidelines:"
          
          GUIDELINES=$(cat .github/claude_code_prompts/doc_enhancement_prompt.md 2>/dev/null || echo "Please enhance the documentation with practical examples, error handling information, and useful FAQ entries.")
          
          # Handle multiline strings for GITHUB_OUTPUT
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "prompt_content<<$EOF" >> $GITHUB_OUTPUT
          echo "$PROMPT_HEADER" >> $GITHUB_OUTPUT
          echo "$GUIDELINES" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      
      - name: Enhance documentation with Claude
        if: steps.changed_files.outputs.files != ''
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt: ${{ steps.dynamic_prompt.outputs.prompt_content }}
          allowed_tools: "View,BatchTool"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
      
      - name: Commit enhanced documentation
        if: steps.changed_files.outputs.files != ''
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          
          if [[ -n $(git status --porcelain) ]]; then
            git add docs/block-reference/
            git commit -m "chore: enhance documentation with examples and details"
            git push origin update-block-docs
          fi