name: Build/Publish Develop Docs
on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for proper versioning
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.15"
      - name: Load cached Poetry installation
        id: cached-poetry
        uses: actions/cache@v3
        with:
          path: ~/.local # the path depends on the OS
          key: poetry-0 # increment to reset cache
      - name: Install Poetry
        if: steps.cached-poetry.outputs.cache-hit != 'true'
        uses: snok/install-poetry@v1
      - name: Install library
        run: poetry install --no-interaction --only docs
      - name: Prepare gh-pages branch
        run: |
          git fetch origin gh-pages --depth=1 || true
      - name: Debug Git State
        run: |
          echo "Current branch:"
          git branch -a
          echo "Git status:"
          git status
          echo "Mike versions:"
          poetry run mike list || echo "No versions found"
      - name: Build Docs Website
        run: |
          poetry run mike deploy --push dev
          poetry run mike alias dev latest --push
