name: Python package release

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      contents: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # fetch a sufficient commit history to detect version changes

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install toml
          python -m pip install poetry==1.8.3
          python -m poetry config virtualenvs.create false
          python -m poetry install

      - name: Get version from pyproject.toml
        run: python -m poetry version $(python -c 'import toml; print(toml.load("pyproject.toml")["tool"]["poetry"]["version"])').dev+$(git rev-parse --short HEAD)

      - name: Build package
        run: python -m poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
